---
# install_ansible_dependencies_for_SELINUX/tasks/main.yml

- name: 'Install required packages on RHEL/CentOS 7'
  ansible.builtin.package:
    name:
      - 'libselinux-python'
      - 'setroubleshoot-server'
      - 'selinux-policy'
    state: 'present'
  when:
    - 'ansible_distribution == "CentOS" or ansible_distribution == "RedHat"'
    - 'ansible_distribution_major_version == "7"'

- name: 'Install required packages on RHEL/CentOS/AlmaLinux/RockyLinux 8'
  ansible.builtin.package:
    name:
      - 'python3-libselinux'
      - 'setroubleshoot-server'
      - 'selinux-policy'
    state: 'present'
  when:
    - 'ansible_os_family == "RedHat" or ansible_os_family == "Rocky"'
    - 'ansible_distribution_major_version == "8"'

- name: 'Install required packages on RHEL/CentOS/AlmaLinux/RockyLinux 9'
  ansible.builtin.package:
    name:
      - 'python3-libselinux'
      - 'setroubleshoot-server'
      - 'selinux-policy'
    state: 'present'
  when:
    - 'ansible_os_family == "RedHat" or ansible_os_family == "Rocky"'
    - 'ansible_distribution_major_version == "9"'

- name: 'Install required packages on openSUSE MicroOS'
  ansible.builtin.package:
    name:
      - 'python3-selinux'
      - 'python3-semanage'
      - 'libselinux1'
      - 'selinux-tools'
      - 'selinux-policy'
      - 'patterns-microos-selinux'
    state: 'present'
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'
  when:
    - 'ansible_os_family == "openSUSE MicroOS"'
